### ISSUE TITLE
Code Elevator

### ISSUE THREAD

**Issue by dmschneider** [FRCTeam1719/2015Robot#1]
Elevator code for production robot:
- [x] multiple set points controlled by potentiometer
- [x] limit switches at top and bottom of travel
- [x] spike to control motor
- [X] Stepping mode
- [x]  Write Test
- [ ]  Implement Variable Speeds (Need more info from drive/device/who the fuck ever)
- [ ] Actually test the elevator

**Comment by dmschneider** [comment]
Code has been merged into master but needs to be commented.

**Comment by Junie-774** [comment]
Elevator motor now tops at every full turn of the potentiometer

**Comment by DGoldDragon28** [comment]
Make sure you're extending `org.usfirst.team1719.subsystems.DualimitedSpike` so as to optimize code.

**Comment by aaronjeline** [comment]
Steps:
- Code complete, tuning required

Freemove:
- Yet to be implemented

**Comment by aaronjeline** [comment]
initDefaultCommand Issue fixed.

**Comment by aaronjeline** [comment]
Passed test bench
