### ISSUE TITLE
Avoid Knocking Over Stacked Bins

### ISSUE THREAD

**Issue by dmschneider** [FRCTeam1719/2015Robot#10]
Use LIDAR sensor to determine if we are about to knock over a stack of bins.

Sensor may be mounted on a rotating platform to allow checking in any direction - although it may get reflections from parts of the robot which will make this difficult to do.
- [x] Protected mode
- [x] Mode tested
- [x] Automatic mode toggle
- [x] Manual toggle
- [x] Smartdashboard supertoggle
- [x] Final Test

**Comment by aaronjeline** [comment]
Code was finalized, but still needs to merged.

**Comment by aaronjeline** [comment]
Also, it needs to be disabled when a claw is opened

**Comment by DGoldDragon28** [comment]
Merged; still must be claw-disabled

**Comment by DGoldDragon28** [comment]
Implemented manual override; must be tested.

**Comment by aaronjeline** [comment]
Duncan finished and tested this today
