### ISSUE TITLE
Pit Tests

### ISSUE THREAD

**Issue by jnmd1999** [FRCTeam1719/2015Robot#16]
- [x] Display all sensor output
- [x] Run through the elevators, preset levels
- [x] Test Vision
- [x] Test Fisher
- [x] Test Claws
- [x] Test camera control
- [x] Drive test

**Comment by DGoldDragon28** [comment]
Done

**Comment by aaronjeline** [comment]
Not quite finished yet, test infrastructure in place, but a test for every subsystem has not yet been created

**Comment by dmschneider** [comment]
Kyle finished the claws test, so all items are complete.
