### ISSUE TITLE
Autonomous

### ISSUE THREAD

**Issue by dmschneider** [FRCTeam1719/2015Robot#4]
Move to recycling bin
Grab and pull back to our side
- [x] Keep camera steady
- [x] Mode 1
  - [x] Deploy fisher
  - [x] Get container
  - [x] Lineup with next container
- [x] Mode 2
  - [x] Move back into auto-zone
- [x] Mode 3
  - [x] Do nothing

**Comment by aaronjeline** [comment]
Add a swapper in the dashboard

**Comment by DGoldDragon28** [comment]
Done some things (see checkboxes)

**Comment by DGoldDragon28** [comment]
Added Autonomous mode 1.

**Comment by DGoldDragon28** [comment]
Mode 2 added; needs testing.

**Comment by aaronjeline** [comment]
Duncan tested mode 2
