### ISSUE TITLE
Vision Code

### ISSUE THREAD

**Issue by dmschneider** [FRCTeam1719/2015Robot#5]
Vision code to identify trash can
Set smart dashboard value(s) when identified 
- [x] See trashcan
- [x] Easy tuning
- [ ] Swing video
- [ ] Smartdashboard coms

**Comment by aaronjeline** [comment]
Preliminary detection of the recycling containers, using the counting of non-zero bits in a binary image

**Comment by aaronjeline** [comment]
- Tuning
- Added GUI for easier tuning

**Comment by dmschneider** [comment]
Closed because we are not using this in our code this year.

**Comment by ChloeEWE** [comment]
we arent?

**Comment by dmschneider** [comment]
No, we are not - it isn't necessary.  We are using the LIDAR to identify
the distance to the recycling bin and then using it again to find the
second recycling bin after we have dealt with the first one.

David

**Comment by ChloeEWE** [comment]
oaoh okay cool

On Sun, Feb 15, 2015 at 5:47 PM, dmschneider notifications@github.com
wrote:

> No, we are not - it isn't necessary. We are using the LIDAR to identify
> the distance to the recycling bin and then using it again to find the
> second recycling bin after we have dealt with the first one.
> 
> David
> 
> On Sun, Feb 15, 2015 at 5:41 PM, ChloeEWE notifications@github.com
> wrote:
> 
> > we arent?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/FRCTeam1719/2015Robot/issues/5#issuecomment-74441522
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FRCTeam1719/2015Robot/issues/5#issuecomment-74441775.

## 

```

greetings and whatever, i don't know how i should sign off a letter,
Chloe
```
