### ISSUE TITLE
Modify drive so that robot can turn left while driving.

### ISSUE THREAD

**Issue by DGoldDragon28** [FRCTeam1719/2015Robot#8]

**Comment by DGoldDragon28** [comment]
I AM A FUCKING SCRUB!!!!!!!!
![iamafuckingscrub](https://cloud.githubusercontent.com/assets/8171483/5821825/fb333ea6-a09c-11e4-8c80-29b731a9023d.png)
Should be '!=' instead of '>'. That's why you can't turn left. Will fix immediately.

**Comment by dmschneider** [comment]
Above code correc

**Comment by dmschneider** [comment]
This issue now only relates to turning to the left.  Tuning the PID will be written up separately.
