### ISSUE TITLE
Tune PID code to strafe straight

### ISSUE THREAD

**Issue by dmschneider** [FRCTeam1719/2015Robot#9]
- [ ]  PID for teleop
- [ ] PID for autonomous

**Comment by aaronjeline** [comment]
Added constants to dashboard for easier tuning

**Comment by DGoldDragon28** [comment]
Finished tuning for _this_ chassis; next one will probably need to be re-tuned.

**Comment by aaronjeline** [comment]
Retune

**Comment by DGoldDragon28** [comment]
Done
